spring:
  application:
    name: redis2-service
  data:
    redis:
      host: localhost
      port: 63792
      username: default
      password:
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop 옵션이 있으며, 스프링 종료 시 컨테이너 종료 여부를 결정할 수 있음
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      file: compose.yaml
